### ISSUE TITLE
Changes in quoting feature

### ISSUE THREAD

**Issue by hakha3** [vck3000/ProAvalon#81] opened 2018-09-21 12:27 UTC
I dont think that quoting feature is that spammy that we need set maximum lines, but if so then make max 6 instead of 5.
And when someone try put text with more "[" than it is maximum, just dont run quoting feature, instead of cutting text. So when someone try say for example : _[a[b[c[d[e[f[g_ it will just say:
_hakha3: [a[b[c[d[e[f[g_
instead of using quoting feature and cutting text:
_hakha3: Quoting:
[a
[b
[c
[d
[e_

**Comment by bocaben** [comment] 2018-09-23 00:42
duplicate of #57? i think leave a comment there and close this issue instead.

**Comment by vck3000** [comment] 2018-09-27 03:06
duplicate of #57

**Closed by vck3000** 2018-09-27 03:06 UTC
